### ISSUE TITLE
twitter handle printing

### ISSUE THREAD

**Issue by susanlovaglio** [learn-co-curriculum/swift-optionals-reading#3]
in the section for the if let method of unwrapping it shows an example of twitter being equal to nil. then an attempt to print but mentions that it won't because it fails. but it actually just prints the word nil.
this:
`if let twitter = twitter {
    print("Twitter: \(twitter)")
}`

prints out this:
`Twitter: nil`

that if/else statement will be different to print out `--no twitter handle--`

like maybe:

`if let twitter = twitter{ 
      print("Twitter: \(twitter)")
 }else if(twitter == nil){
     print("--no twitter handle--")
 }`

**Comment by markedwardmurray** [comment]
hm, that's interesting. this lesson was written using a Swift 2.1 playground. Are you working in Xcode 7.3 with Swift 2.2? It's possible that the update earlier this week affected the behavior of the language.

**Comment by susanlovaglio** [comment]
I'm working in Swift 2.1.1 playground and Xcode 7.2. 
Maybe an update from 2.1 to 2.1.1.

**Comment by susanlovaglio** [comment]
Oh wait, I didn't have it written correctly. I changed a piece and didn't put it back. My bad!

**Comment by markedwardmurray** [comment]
haha, or that, yup! #normaldayinprogramming
